"""initial schema

Revision ID: 6457f024f5e7
Revises: 
Create Date: 2026-09-28 14:26:49.414978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6457f024f5e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderators_username'), 'moderators', ['username'], unique=True)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_code_hash', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', 'CLOSED', name='report_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_case_code_hash'), 'reports', ['case_code_hash'], unique=True)
    op.create_table('status_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', 'CLOSED', name='report_status_enum', native_enum=False), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_updates_report_id'), 'status_updates', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_updates_report_id'), table_name='status_updates')
    op.drop_table('status_updates')
    op.drop_index(op.f('ix_reports_case_code_hash'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_moderators_username'), table_name='moderators')
    op.drop_table('moderators')
    # ### end Alembic commands ###
